# Generated by Django 4.2.4 on 2023-08-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('want_to_play', models.BooleanField(default=False)),
                ('playing', models.BooleanField(default=False)),
                ('beaten', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('dropped', models.BooleanField(default=False)),
            ],
        ),
    ]
