# Generated by Django 4.2.4 on 2023-08-30 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews_app', '0001_initial'),
        ('game_app', '0002_delete_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('reviews', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews_app.reviews')),
            ],
        ),
    ]
