# Generated by Django 4.2.4 on 2023-09-04 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='reviews',
        ),
    ]
