# Generated by Django 4.2.4 on 2024-02-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='game_status',
            field=models.CharField(default='currently_playing'),
        ),
    ]
