# Generated by Django 4.2.4 on 2024-02-19 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0001_initial'),
        ('reviews_app', '0002_alter_review_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='game_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='collections_app.collection'),
        ),
    ]
