# Generated by Django 4.2.4 on 2024-02-19 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0003_alter_review_game_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='game_status',
        ),
    ]
