# Generated by Django 4.2.4 on 2023-09-04 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0004_alter_reviews_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='game',
            new_name='game_id',
        ),
    ]
