# Generated by Django 4.2.4 on 2023-09-04 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0009_alter_collection_game'),
        ('reviews_app', '0005_rename_game_reviews_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='game_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='collections_app.collection'),
        ),
    ]
