# Generated by Django 4.2.4 on 2023-08-30 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('game', models.IntegerField(primary_key=True, serialize=False)),
                ('currently_playing', models.BooleanField(default=False)),
                ('beaten', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('dropped', models.BooleanField(default=False)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
