# Generated by Django 4.2.4 on 2023-08-31 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='beaten',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='currently_playing',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='dropped',
        ),
        migrations.AddField(
            model_name='collection',
            name='status',
            field=models.CharField(choices=[('playing', 'Currently Playing'), ('beaten', 'Beaten'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='playing', max_length=20),
        ),
    ]
