# Generated by Django 4.2.4 on 2023-08-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0006_alter_collection_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='status',
            field=models.CharField(choices=[('currently_playing', 'currently_playing'), ('beaten', 'beaten'), ('completed', 'completed'), ('dropped', 'dropped')], default='currently_playing', max_length=20),
        ),
    ]
