# Generated by Django 4.2.4 on 2023-08-31 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0007_alter_collection_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='status',
        ),
        migrations.AddField(
            model_name='collection',
            name='game_status',
            field=models.CharField(default='currently_playing'),
        ),
    ]
