# Generated by Django 4.2.4 on 2023-08-31 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0008_remove_collection_status_collection_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='game',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
