# Generated by Django 4.2.4 on 2023-08-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backlog',
            name='id',
        ),
        migrations.AlterField(
            model_name='backlog',
            name='game',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
